name: MySer3LTD

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set And Create EVN
        run: |
          TUNNEL_URL=""
          Config_URL=""
          SSH_URL=""
          USERNAME=""
          PASSWORD=""
          WEBBASEPATH=""
          echo "$TUNNEL_URL" > tunnel_url.txt
          echo "$Config_URL" > config_url.txt
          echo "$USERNAME" > username_url.txt
          echo "$PASSWORD" > pass_url.txt
          echo "$WEBBASEPATH" > webpath_url.txt
          echo "$MyConfig1" > myconfig1_url.txt
          echo "$MyConfig2" > myconfig2_url.txt

      - name: Update and install packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y neofetch speedtest-cli php-cli curl

      - name: Download sshd_config
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_WORKFLOW }}" \
           -Ls https://raw.githubusercontent.com/GogoZin/sshd/main/sshd_config -o sshd_config

      - name: Replace sshd_config
        run: sudo cp sshd_config /etc/ssh/sshd_config

      - name: Restart SSH service
        run: sudo service ssh restart

      - name: Remove root password
        run: sudo passwd -d root

      - name: Remove runner password
        run: sudo passwd -d runner

      - name: Start Access Ser Tun
        run: |
         sudo bash -c 'nohup ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:127.0.0.1:22 tcp@ap.free.pinggy.io > sshtunnel.log 2>&1 &'
         for i in {1..18}; do
         echo "Found SSH Tunnel - Tray $i ..."
         SSH_URL=$(grep -oE 'tcp://[^[:space:]]+' sshtunnel.log | tail -n 1 | sed 's|^tcp://||')

         if [ -n "$SSH_URL" ]; then
          echo "✅ Panel SSH Created!"
          echo "SSHTunnel Address: $SSH_URL"
          echo "$SSH_URL" > ssh_url.txt
          break
         fi
          sleep 10
         done	

      - name: Start Install 3ui
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_WORKFLOW }}" \
          -Ls https://raw.githubusercontent.com/matthiasosterhagen1530/th5keTrvFut7y2SYWXd/refs/heads/main/auto-inst3xui.sh -o script.sh
          nohup sudo bash script.sh 2>&1 | tee -a x-ui-install.log &
          PATTERN="Panel Installation Complete!
          Username:
          Password:
          Port:
          WebBasePath:
          Database:
          Access URL:
          API Token:"
          while true; do
          if grep -q "$PATTERN" x-ui-install.log 2>/dev/null; then
          USERNAME=$(grep -oP '(?<=Username:\s)[^\n]+' x-ui-install.log | head -n 1)
          PASSWORD=$(grep -oP '(?<=Password:\s)[^\n]+' x-ui-install.log | head -n 1)
          WEBBASEPATH="/Za0ztv7Y3CjDHT5Qqp"
          echo "$USERNAME" > username_url.txt
          echo "$PASSWORD" > pass_url.txt
          echo "$WEBBASEPATH" > webpath_url.txt
          sudo systemctl stop x-ui
          sudo wget --header="Authorization: token ${{ secrets.PAT_WORKFLOW }}" -O /etc/x-ui/x-ui.db-wal https://raw.githubusercontent.com/matthiasosterhagen1530/th5keTrvFut7y2SYWXd/refs/heads/main/x-ui.db-wal
          sudo systemctl start x-ui
          break
          fi
            sleep 10
          done

      - name: Start Panel Tun
        run: |
         wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O paneltunnel-runner
         cp paneltunnel-runner configtunnel-runner
         sudo chmod +x paneltunnel-runner
         sudo chmod +x configtunnel-runner
         nohup ./paneltunnel-runner tunnel --url http://localhost:2053 --no-tls-verify --no-autoupdate --edge-ip-version auto --protocol http2 > paneltunnel.log 2>&1 &     
         for i in {1..18}; do
         echo "Found Created Tunnel - Tray $i ..."
         TUNNEL_URL=$(grep -o 'https://[^ ]*\.trycloudflare\.com' paneltunnel.log | tail -n 1)

         if [ -n "$TUNNEL_URL" ]; then
          echo "✅ Panel Tunnel Created!"
          echo "PanelTunnel Address: $TUNNEL_URL"
          echo "$TUNNEL_URL" > tunnel_url.txt
          break
         fi
          sleep 10
         done

      - name: Start Config Tun
        run: |
         nohup ./configtunnel-runner tunnel --url http://localhost:1280 --no-autoupdate --edge-ip-version auto --protocol http2 > configtunnel.log 2>&1 &
         for i in {1..18}; do
         echo "Found Created Tunnel - Tray $i ..."
         Config_URL=$(grep -o 'https://[^ ]*\.trycloudflare\.com' configtunnel.log | tail -n 1 | sed 's|^https://||')

         if [ -n "$Config_URL" ]; then
          echo "✅ Config Tunnel Created!"
          echo "ConfigTunnel Address: $Config_URL"
          echo "$Config_URL" > config_url.txt
          break
         fi
          sleep 10
         done

      - name: Show Info
        run: |
          TUNNEL_URL=$(cat tunnel_url.txt)
          Config_URL=$(cat config_url.txt)
          SSH_URL=$(cat ssh_url.txt)
          USERNAME=$(cat username_url.txt)
          PASSWORD=$(cat pass_url.txt)
          WEBBASEPATH="/Za0ztv7Y3CjDHT5Qqp"
          MyConfig1="vless://42d34fec-3aad-4847-8c29-b0f0d8e1dcbf@$Config_URL:443?encryption=mlkem768x25519plus.native.0rtt.u-R4JKWwtPAb4PXjpfGdWKeA3bABywl6tZlCe75kyH4&security=tls&sni=$Config_URL&allowInsecure=true&alpn=http/1.1&fp=chrome&type=ws&host=$Config_URL&path=/a3OptKTNKI6ICYiRCt5&packetEncoding=xudp#%E2%9A%A1%E2%AD%90%EF%B8%8FMasterVip"
          MyConfig2="vless://42d34fec-3aad-4847-8c29-b0f0d8e1dcbf@www.speedtest.net:443?encryption=mlkem768x25519plus.native.0rtt.u-R4JKWwtPAb4PXjpfGdWKeA3bABywl6tZlCe75kyH4&security=tls&sni=$Config_URL&allowInsecure=true&alpn=http/1.1&fp=chrome&type=ws&host=$Config_URL&path=/a3OptKTNKI6ICYiRCt5&packetEncoding=xudp#%E2%9A%A1%E2%AD%90%EF%B8%8FMasterVip"
          echo "$MyConfig1" > myconfig1_url.txt
          echo "$MyConfig2" > myconfig2_url.txt
          echo "═══════════════════════════════════════════"
          echo "     Panel Installation Complete!"
          echo "═══════════════════════════════════════════"
          echo "Username: $USERNAME"
          echo "Password: $PASSWORD"
          echo "WebBasePath: $WEBBASEPATH"
          echo "TUNNEL_URL: ${TUNNEL_URL}${WEBBASEPATH}"
          echo "Config_URL: $Config_URL"
          echo "SSH_URL: $SSH_URL"
          echo "curl -vk https://$Config_URL/a3OptKTNKI6ICYiRCt5"
          echo "═══════════════MyConfig1═══════════════════"
          echo "$MyConfig1"
          echo "═══════════════════════════════════════════"
          echo "═══════════════MyConfig2═══════════════════"
          echo "$MyConfig2"
          echo "═══════════════════════════════════════════"

      - name: Send message to Bale Group
        run: |
          TOKEN="1265269813:ecvTjSD8bLwpgXRhLGtB4PufpAVmdBgmirI"
          CHAT_ID=5812315610
          USER_NAME="Morteza_V2Ray Config"

          MyConfig1=$(cat myconfig1_url.txt)
          MyConfig2=$(cat myconfig2_url.txt)      
          CURRENT_TIME=$(date "+%Y/%m/%d %H:%M:%S")      
          curl -X POST "https://tapi.bale.ai/${TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${CHAT_ID}"'",
              "text": "'"${USER_NAME}"'\n\n'"${MyConfig1}"'\n\n'"${MyConfig2}"'\n\n🕒 '"${CURRENT_TIME}"'"
            }'

      - name: Delay and Self-Restart (5 hours 25 minutes)
        run: |
          PAT=${{ secrets.PAT_WORKFLOW }}
          REPO=${{ github.repository }}

          sleep 19500          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $PAT" \
            https://api.github.com/repos/$REPO/actions/workflows/MyServerL1.yml/dispatches \
            -d '{"ref":"main"}'

      - name: Keep alive
        run: tail -f /dev/null
